import { Buffer } from "buffer";
import React from "react";
import ReactDOM from "react-dom";
import CssBaseline from "@material-ui/core/CssBaseline";
import * as serviceworker from './serviceWorker';
import App from "./App";
import AppErrorBoundary from "./components/AppErrorBoundary";
import { installGlobalErrorReporting } from "./services/clientErrorReporter";
import "./styles/konnex-signal.css";

window.Buffer = Buffer;
installGlobalErrorReporting();

ReactDOM.render(
	<CssBaseline>
		<AppErrorBoundary>
			<App />
		</AppErrorBoundary>
	</CssBaseline>,
	document.getElementById("root"),
	() => {
		window.finishProgress();
	}
);

// No service worker is generated by the current build. Remove registrations
// left by previous releases so stale bundles cannot blank the application.
serviceworker.unregister();
